os: linux

language: python
python:
    - "2.7"
    - "3.5"

sudo: required
dist: trusty

before_install:
    sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
    wget https://github.com/glfw/glfw/releases/download/3.1.1/glfw-3.1.1.zip;
    sudo apt-get update;

    sudo apt-get install -qq build-essential xorg-dev libglu1-mesa-dev libglew-dev libglm-dev;
    sudo apt-get install -qq cmake;
    sudo apt-get install -qq libusb-1.0-0-dev;

    cmake --version;

    unzip glfw-3.1.1.zip;
    cd glfw-3.1.1;
    sudo cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON;
    sudo make;
    sudo make install;
    cd ..;

    git clone https://github.com/IntelRealSense/librealsense.git;
    cd librealsense;
    git checkout v1.12.1;
    mkdir build;
    cd build;
    cmake ..;
    make;
    sudo make install;
    sudo ldconfig;
    cd ..;
    cd ..;


install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - cd tests
    - nosetests test_offline.py

